### ISSUE TITLE
Red-Mobile on Android - where to find the settings.js ?

### ISSUE THREAD

**Issue by YEUAM** [okhiroyuki/red-mobile-nodes#34]
Hello ,

where on the Android Device can i find  the  settings.js  of the NodeRed Project ?

I would like to change things like the "page title" and "header title".

**Comment by okhiroyuki** [comment]
@YEUAM 
Hello.

This repository is not for RedMobile.

If you have any requests, please ask in the forum.
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/redmobile-apps
